// <auto-generated />
using System;
using EnsaPlatform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnsaPlatform.Migrations
{
    [DbContext(typeof(EnsaContext))]
    partial class EnsaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EnsaPlatform.Models.Absence", b =>
                {
                    b.Property<int>("AbsenceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EtudiantID")
                        .HasColumnType("int");

                    b.Property<int>("Present")
                        .HasColumnType("int");

                    b.Property<int>("SceanceID")
                        .HasColumnType("int");

                    b.HasKey("AbsenceID");

                    b.HasIndex("EtudiantID");

                    b.HasIndex("SceanceID");

                    b.ToTable("Absence");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Administration", b =>
                {
                    b.Property<int>("AdministrationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADDRESSE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DATE_NAISSANCE")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIEU_NAISSANCE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRENOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdministrationID");

                    b.ToTable("Administration");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Departement", b =>
                {
                    b.Property<int>("DepartementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TITRE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartementID");

                    b.ToTable("Departement");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Etudiant", b =>
                {
                    b.Property<int>("EtudiantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADDRESSE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DATE_NAISSANCE")
                        .HasColumnType("datetime2");

                    b.Property<int>("DELEGUE")
                        .HasColumnType("int");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIEU_NAISSANCE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NiveauID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PRENOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EtudiantID");

                    b.HasIndex("NiveauID");

                    b.ToTable("Etudiant");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Matiere", b =>
                {
                    b.Property<string>("MatiereID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProfesseurID")
                        .HasColumnType("int");

                    b.Property<string>("TITRE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MatiereID");

                    b.HasIndex("ProfesseurID");

                    b.ToTable("Matiere");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Module", b =>
                {
                    b.Property<string>("ModuleID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatiereID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProfesseurID")
                        .HasColumnType("int");

                    b.Property<string>("TITRE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModuleID");

                    b.HasIndex("MatiereID");

                    b.HasIndex("ProfesseurID");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Module_Matiere", b =>
                {
                    b.Property<int>("Module_MatiereID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MatiereID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModuleID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Module_MatiereID");

                    b.HasIndex("MatiereID");

                    b.HasIndex("ModuleID");

                    b.ToTable("Module_Matieres");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Module_Niveau", b =>
                {
                    b.Property<int>("Module_NiveauID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ModuleID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NiveauID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Module_NiveauID");

                    b.HasIndex("ModuleID");

                    b.HasIndex("NiveauID");

                    b.ToTable("Module_Niveaus");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Niveau", b =>
                {
                    b.Property<string>("NiveauID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FILIERE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfesseurID")
                        .HasColumnType("int");

                    b.Property<string>("TITRE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NiveauID");

                    b.HasIndex("ProfesseurID");

                    b.ToTable("Niveau");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Note", b =>
                {
                    b.Property<int>("NoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EtudiantID")
                        .HasColumnType("int");

                    b.Property<string>("MatiereID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("NoteMatiere")
                        .HasColumnType("real");

                    b.HasKey("NoteID");

                    b.HasIndex("EtudiantID");

                    b.HasIndex("MatiereID");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Professeur", b =>
                {
                    b.Property<int>("ProfesseurID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADDRESSE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHEF_DEPARTEMENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DATE_NAISSANCE")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartementID")
                        .HasColumnType("int");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIEU_NAISSANCE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRENOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfesseurID");

                    b.HasIndex("DepartementID");

                    b.ToTable("Professeur");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Sceance", b =>
                {
                    b.Property<int>("SceanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DATE_HEURE")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatiereID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NiveauID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProfesseurID")
                        .HasColumnType("int");

                    b.HasKey("SceanceID");

                    b.HasIndex("MatiereID");

                    b.HasIndex("NiveauID");

                    b.HasIndex("ProfesseurID");

                    b.ToTable("Sceance");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Absence", b =>
                {
                    b.HasOne("EnsaPlatform.Models.Etudiant", "Etudiant")
                        .WithMany("Absences")
                        .HasForeignKey("EtudiantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnsaPlatform.Models.Sceance", "Sceance")
                        .WithMany("Absences")
                        .HasForeignKey("SceanceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etudiant");

                    b.Navigation("Sceance");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Etudiant", b =>
                {
                    b.HasOne("EnsaPlatform.Models.Niveau", "Niveau")
                        .WithMany("Etudiants")
                        .HasForeignKey("NiveauID");

                    b.Navigation("Niveau");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Matiere", b =>
                {
                    b.HasOne("EnsaPlatform.Models.Professeur", "Professeur")
                        .WithMany("Matieres")
                        .HasForeignKey("ProfesseurID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professeur");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Module", b =>
                {
                    b.HasOne("EnsaPlatform.Models.Matiere", null)
                        .WithMany("Module_Matieres")
                        .HasForeignKey("MatiereID");

                    b.HasOne("EnsaPlatform.Models.Professeur", "Professeur")
                        .WithMany("Modules")
                        .HasForeignKey("ProfesseurID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professeur");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Module_Matiere", b =>
                {
                    b.HasOne("EnsaPlatform.Models.Matiere", "Matiere")
                        .WithMany()
                        .HasForeignKey("MatiereID");

                    b.HasOne("EnsaPlatform.Models.Module", "Module")
                        .WithMany("Module_Matieres")
                        .HasForeignKey("ModuleID");

                    b.Navigation("Matiere");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Module_Niveau", b =>
                {
                    b.HasOne("EnsaPlatform.Models.Module", "Module")
                        .WithMany("Module_Niveaus")
                        .HasForeignKey("ModuleID");

                    b.HasOne("EnsaPlatform.Models.Niveau", "Niveau")
                        .WithMany("Module_Niveaus")
                        .HasForeignKey("NiveauID");

                    b.Navigation("Module");

                    b.Navigation("Niveau");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Niveau", b =>
                {
                    b.HasOne("EnsaPlatform.Models.Professeur", "Professeur")
                        .WithMany("Niveaux")
                        .HasForeignKey("ProfesseurID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professeur");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Note", b =>
                {
                    b.HasOne("EnsaPlatform.Models.Etudiant", "Etudiant")
                        .WithMany("Notes")
                        .HasForeignKey("EtudiantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnsaPlatform.Models.Matiere", "Matiere")
                        .WithMany("Notes")
                        .HasForeignKey("MatiereID");

                    b.Navigation("Etudiant");

                    b.Navigation("Matiere");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Professeur", b =>
                {
                    b.HasOne("EnsaPlatform.Models.Departement", "Departement")
                        .WithMany("Professeurs")
                        .HasForeignKey("DepartementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departement");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Sceance", b =>
                {
                    b.HasOne("EnsaPlatform.Models.Matiere", "Matiere")
                        .WithMany("Sceances")
                        .HasForeignKey("MatiereID");

                    b.HasOne("EnsaPlatform.Models.Niveau", "Niveau")
                        .WithMany("Sceances")
                        .HasForeignKey("NiveauID");

                    b.HasOne("EnsaPlatform.Models.Professeur", "Professeur")
                        .WithMany("Sceances")
                        .HasForeignKey("ProfesseurID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matiere");

                    b.Navigation("Niveau");

                    b.Navigation("Professeur");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Departement", b =>
                {
                    b.Navigation("Professeurs");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Etudiant", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Matiere", b =>
                {
                    b.Navigation("Module_Matieres");

                    b.Navigation("Notes");

                    b.Navigation("Sceances");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Module", b =>
                {
                    b.Navigation("Module_Matieres");

                    b.Navigation("Module_Niveaus");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Niveau", b =>
                {
                    b.Navigation("Etudiants");

                    b.Navigation("Module_Niveaus");

                    b.Navigation("Sceances");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Professeur", b =>
                {
                    b.Navigation("Matieres");

                    b.Navigation("Modules");

                    b.Navigation("Niveaux");

                    b.Navigation("Sceances");
                });

            modelBuilder.Entity("EnsaPlatform.Models.Sceance", b =>
                {
                    b.Navigation("Absences");
                });
#pragma warning restore 612, 618
        }
    }
}
